spring.application.name=projet
server.port=8089

# configuration de la base données
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/Grosses?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-null-for-primitives=false